import en from "@/locales/en.json"

export type MessageKey = keyof typeof en

type Messages = Record<string, string>

const localeCache: Record<string, Messages> = { en }

/**
 * Default copy helper — always returns English.
 * Use this in server components that don't have a user locale yet (e.g. auth page).
 */
export function copy(key: MessageKey): string {
  return en[key]
}

/**
 * Load a locale file dynamically. Returns English as fallback if the
 * target locale file doesn't exist (translation not generated yet).
 */
async function loadLocale(locale: string): Promise<Messages> {
  if (localeCache[locale]) return localeCache[locale]

  try {
    // Dynamic import — works for locales generated by `lingo.dev run`
    const mod = await import(`@/locales/${locale}.json`)
    const messages = mod.default as Messages
    localeCache[locale] = messages
    return messages
  } catch {
    // Locale file doesn't exist yet; fall back to English
    return en
  }
}

/**
 * Locale-aware copy helper. Loads the requested locale and returns
 * the translated string, falling back to English if not available.
 *
 * Usage in server components:
 *   const label = await localizedCopy("onboarding.submit", profile.preferredLanguage)
 */
export async function localizedCopy(
  key: MessageKey,
  locale: string
): Promise<string> {
  const messages = await loadLocale(locale)
  return messages[key] ?? en[key]
}
